#!/usr/bin/env python3
"""
training/train_unet.py — Train U-Net radio map completion model.

The U-Net learns to predict a dense radio map from:
  - Terrain conditioning tensor [3, H, W]  (DEM, buildings, vegetation)
  - Sparse RSSI observation map [1, H, W]  (normalised signal strength at sensor positions)
  - Measurement mask             [1, H, W]  (1 where observation exists)

Dataset generated by training/generate_dataset.py (needs sim-engine running).

Usage:
  # Train from scratch
  python training/train_unet.py \\
    --dataset data/datasets/uhf_433_v1/ \\
    --output  data/checkpoints/unet_uhf_v1.pt \\
    --epochs 50 --batch-size 32

  # Fine-tune from checkpoint
  python training/train_unet.py \\
    --dataset data/datasets/uhf_433_v1/ \\
    --resume  data/checkpoints/unet_uhf_v1.pt \\
    --output  data/checkpoints/unet_uhf_v2.pt \\
    --epochs 20

  # After training, export to ONNX for master
  python scripts/export_onnx.py --model unet \\
    --checkpoint data/checkpoints/unet_uhf_v1.pt \\
    --output data/checkpoints/unet_uhf_v1.onnx

Requirements:
  pip install torch numpy tqdm
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train U-Net radio map completion model")
    p.add_argument("--dataset",    type=Path, required=True,
                   help="Path to dataset directory (contains scene_*.npz)")
    p.add_argument("--val-dataset", type=Path, default=None,
                   help="Separate validation directory (default: --dataset/val/ or split)")
    p.add_argument("--output",     type=Path, required=True,
                   help="Output .pt checkpoint path")
    p.add_argument("--resume",     type=Path, default=None,
                   help="Resume from existing .pt checkpoint")
    p.add_argument("--epochs",     type=int,  default=50)
    p.add_argument("--batch-size", type=int,  default=32)
    p.add_argument("--lr",         type=float, default=1e-3)
    p.add_argument("--base",       type=int,  default=32,
                   help="U-Net base channel count (32=3M params, 16=800k params)")
    p.add_argument("--val-split",  type=float, default=0.1,
                   help="Fraction of scenes used for validation")
    p.add_argument("--workers",    type=int,  default=4)
    p.add_argument("--device",     default="auto",
                   help="cpu | cuda | auto")
    p.add_argument("--export-onnx", action="store_true",
                   help="Export ONNX after training (requires --output to be .pt)")
    p.add_argument("--loss",       default="mse+l1",
                   choices=["mse+l1", "bce"],
                   help="Loss: mse+l1 (radio map target) | bce (heatmap target)")
    p.add_argument("--pos-weight", type=float, default=20.0,
                   help="BCE positive class weight (upweight emitter pixels, default 20)")
    p.add_argument("--dropout",    type=float, default=0.0,
                   help="Spatial dropout at bottleneck (0=none, 0.1-0.3 for noisy sim data)")
    p.add_argument("--seed",       type=int,  default=42)
    return p.parse_args()


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------


def _load_scene(path: Path) -> tuple | None:
    """
    Load one .npz scene and return (input_tensor [5,H,W], target [1,H,W]).
    Returns None on error.
    """
    import numpy as np
    try:
        d = np.load(path)
        cond    = d["conditioning"]   # [3, H, W]
        rssi_m  = d["rssi_map"]       # [H, W]
        rssi_mk = d["rssi_mask"]      # [H, W]
        gt      = d["radiomap_gt"]    # [H, W]

        # Stack into [5, H, W]
        inp = np.concatenate([
            cond,
            rssi_m[np.newaxis],
            rssi_mk[np.newaxis],
        ], axis=0).astype("float32")
        inp = np.nan_to_num(inp, nan=0.0, posinf=1.0, neginf=0.0)

        tgt = gt[np.newaxis].astype("float32")  # [1, H, W]
        tgt = np.nan_to_num(tgt, nan=0.0, posinf=1.0, neginf=0.0)
        return inp, tgt
    except Exception as exc:
        print(f"  WARN: failed to load {path}: {exc}")
        return None


class RadioMapDataset:
    """
    Minimal dataset that loads .npz files on demand.
    Compatible with torch.utils.data.DataLoader.
    """

    def __init__(self, scene_paths: list[Path]) -> None:
        self._paths = scene_paths

    def __len__(self) -> int:
        return len(self._paths)

    def __getitem__(self, idx: int):
        import numpy as np
        import torch
        result = _load_scene(self._paths[idx])
        if result is None:
            # Return zeros of plausible shape
            return torch.zeros(5, 64, 64), torch.zeros(1, 64, 64)
        inp, tgt = result
        return torch.from_numpy(inp), torch.from_numpy(tgt)


# ---------------------------------------------------------------------------
# Loss
# ---------------------------------------------------------------------------


def combined_loss(pred, target):
    """MSE + L1: MSE for overall accuracy, L1 for spatial sharpness."""
    import torch.nn.functional as F
    return 0.7 * F.mse_loss(pred, target) + 0.3 * F.l1_loss(pred, target)


def bce_loss(pred, target, pos_weight: float = 1.0):
    """
    Soft binary cross-entropy — better for peaked heatmap targets.

    Avoids the 1/N gradient dilution of MSE when the positive region
    (emitter blob) is small compared to the grid.  Use pos_weight > 1
    to further upweight pixels inside the blob.
    """
    import torch
    import torch.nn.functional as F
    eps = 1e-7
    pred_clamp = pred.clamp(eps, 1 - eps)
    bce = -(target * torch.log(pred_clamp) + (1 - target) * torch.log(1 - pred_clamp))
    if pos_weight != 1.0:
        w = 1.0 + (pos_weight - 1.0) * (target > 0.05).float()
        bce = bce * w
    return bce.mean()


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------


def train(args: argparse.Namespace) -> None:
    try:
        import torch
        import torch.optim as optim
        from torch.utils.data import DataLoader
    except ImportError:
        print("ERROR: PyTorch required. pip install torch")
        sys.exit(1)

    from shared.models.unet_arch import UNetRadioMap, count_parameters, export_to_onnx

    # Device
    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)
    print(f"Device: {device}")

    # Reproducibility
    torch.manual_seed(args.seed)
    random.seed(args.seed)

    # Discover scenes
    train_scenes = sorted(args.dataset.glob("scene_*.npz"))
    if not train_scenes:
        print(f"ERROR: No scene_*.npz found in {args.dataset}")
        sys.exit(1)
    random.shuffle(train_scenes)
    print(f"Train dataset: {len(train_scenes)} scenes in {args.dataset}")

    # Validation: explicit --val-dataset, then <dataset>/val/, then random split
    val_dir = args.val_dataset or (args.dataset / "val")
    if val_dir.is_dir():
        val_scenes = sorted(val_dir.glob("scene_*.npz"))
        if val_scenes:
            print(f"Val dataset:   {len(val_scenes)} scenes in {val_dir}")
        else:
            val_scenes = train_scenes[-max(1, int(len(train_scenes)*args.val_split)):]
            train_scenes = train_scenes[:-len(val_scenes)]
    else:
        n_val = max(1, int(len(train_scenes) * args.val_split))
        val_scenes   = train_scenes[-n_val:]
        train_scenes = train_scenes[:-n_val]

    n_train = len(train_scenes)
    n_val   = len(val_scenes)
    train_ds = RadioMapDataset(train_scenes)
    val_ds   = RadioMapDataset(val_scenes)
    print(f"Split: {n_train} train / {n_val} val")

    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True,
        num_workers=args.workers, pin_memory=(device.type == "cuda"),
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.workers,
    )

    # Loss function
    if args.loss == "bce":
        loss_fn = lambda p, t: bce_loss(p, t, pos_weight=args.pos_weight)
        print(f"Loss: BCE  pos_weight={args.pos_weight}")
    else:
        loss_fn = combined_loss
        print("Loss: MSE+L1")

    # Model
    model = UNetRadioMap(in_ch=5, base=args.base, dropout=args.dropout).to(device)
    n_params = count_parameters(model)
    print(f"U-Net: base={args.base}  dropout={args.dropout}  params={n_params/1e6:.2f}M")

    # Resume
    start_epoch = 0
    best_val    = float("inf")
    if args.resume and args.resume.exists():
        ckpt = torch.load(args.resume, map_location=device)
        if isinstance(ckpt, dict) and "model_state" in ckpt:
            model.load_state_dict(ckpt["model_state"])
            start_epoch = ckpt.get("epoch", 0)
            best_val    = ckpt.get("best_val", float("inf"))
            print(f"Resumed from epoch {start_epoch}  best_val={best_val:.4f}")
        else:
            model.load_state_dict(ckpt)
            print("Resumed (bare state_dict)")

    optimizer = optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=args.lr * 0.01
    )
    # Fast-forward scheduler if resuming
    for _ in range(start_epoch):
        scheduler.step()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    best_ckpt = args.output.with_suffix(".best.pt")

    print(f"\nTraining for {args.epochs} epochs  "
          f"(batch={args.batch_size}, lr={args.lr})\n")

    for epoch in range(start_epoch, start_epoch + args.epochs):
        # --- Train ---
        model.train()
        t0      = time.monotonic()
        tr_loss = 0.0
        for inp, tgt in train_loader:
            inp, tgt = inp.to(device), tgt.to(device)
            optimizer.zero_grad()
            pred = model(inp)
            loss = loss_fn(pred, tgt)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            tr_loss += loss.item() * inp.size(0)
        tr_loss /= n_train

        # --- Validate ---
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for inp, tgt in val_loader:
                inp, tgt = inp.to(device), tgt.to(device)
                pred = model(inp)
                val_loss += loss_fn(pred, tgt).item() * inp.size(0)
        val_loss /= n_val

        scheduler.step()
        elapsed = time.monotonic() - t0
        lr_now  = optimizer.param_groups[0]["lr"]

        print(
            f"Epoch {epoch+1:4d}/{start_epoch+args.epochs}  "
            f"train={tr_loss:.4f}  val={val_loss:.4f}  "
            f"lr={lr_now:.2e}  {elapsed:.1f}s"
        )

        # Save checkpoint
        ckpt_data = {
            "model_state": model.state_dict(),
            "epoch":       epoch + 1,
            "best_val":    best_val,
            "args": {
                "base":    args.base,
                "in_ch":   5,
                "dataset": str(args.dataset),
            },
        }
        torch.save(ckpt_data, args.output)

        if val_loss < best_val:
            best_val = val_loss
            torch.save(ckpt_data, best_ckpt)
            print(f"  ✓ New best val={best_val:.4f}  saved → {best_ckpt}")

    print(f"\nTraining done.  Best val={best_val:.4f}")
    print(f"Checkpoint: {args.output}")
    print(f"Best:       {best_ckpt}")

    # Optional ONNX export
    if args.export_onnx:
        onnx_path = args.output.with_suffix(".onnx")
        ckpt = torch.load(best_ckpt, map_location="cpu")
        best_model = UNetRadioMap(in_ch=5, base=args.base)
        best_model.load_state_dict(ckpt["model_state"])
        export_to_onnx(best_model, str(onnx_path), grid_size=256, opset=17)
        print(f"ONNX exported: {onnx_path}")
        print(f"\nDeploy to master:\n"
              f"  cp {onnx_path} data/checkpoints/\n"
              f"  Set MODEL_UNET_PATH=data/checkpoints/{onnx_path.name} in docker-compose.yml")


if __name__ == "__main__":
    train(parse_args())
