"""
shared.messages — Pydantic v2 message schemas for lunchfork inter-service communication.

All messages are serialized as JSON over the CommTransport layer.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class BaseMessage(BaseModel):
    """Base class for all lunchfork messages."""

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class NodePosition(BaseModel):
    """Geographic position of a node."""

    lat: float = Field(..., description="Latitude in decimal degrees (WGS84)")
    lon: float = Field(..., description="Longitude in decimal degrees (WGS84)")
    alt_m: float = Field(..., description="Altitude above MSL in metres")
    accuracy_m: float | None = Field(None, description="Position accuracy (1-sigma) in metres")


class FreqChannel(BaseModel):
    """Frequency channel descriptor."""

    center_hz: int = Field(..., description="Centre frequency in Hz")
    bandwidth_hz: int = Field(..., description="Channel bandwidth in Hz")
    label: str | None = Field(None, description="Human-readable label (e.g. 'UHF-433')")


class RssiMessage(BaseMessage):
    """RSSI measurement from a node — published to rssi/{node_id}."""

    version: str = "1.0"
    node_id: str = Field(..., description="Unique identifier of the publishing node")
    node_type: Literal["ground", "uav", "vehicle"] = Field(..., description="Node platform type")
    timestamp_utc: datetime = Field(..., description="UTC timestamp of the measurement")
    position: NodePosition = Field(..., description="Node position at measurement time")
    freq_channel: FreqChannel = Field(..., description="Frequency channel of the measurement")
    rssi_dbm: float = Field(..., description="Received signal strength in dBm")
    snr_db: float | None = Field(None, description="Signal-to-noise ratio in dB")
    is_simulated: bool = Field(False, description="True if generated by sim-engine")


class NodeStatus(BaseMessage):
    """Periodic node health status — published to node/status/{node_id}."""

    version: str = "1.0"
    node_id: str
    timestamp_utc: datetime
    node_type: Literal["ground", "uav", "vehicle"]
    position: NodePosition
    sdr_ok: bool = Field(..., description="SDR hardware functioning")
    gps_ok: bool = Field(..., description="GPS fix available")
    comm_ok: bool = Field(..., description="Comm transport connected")
    rssi_rate_hz: float = Field(..., description="Current RSSI publish rate in Hz")


class TargetLocation(BaseMessage):
    """Estimated target location from particle filter — published to loc/target/{target_id}."""

    version: str = "1.0"
    target_id: str
    timestamp_utc: datetime
    position: NodePosition
    uncertainty_m: float = Field(..., description="Position uncertainty (1-sigma) in metres")
    covariance: list[list[float]] = Field(..., description="2×2 (or 3×3) covariance matrix")
    n_particles: int = Field(..., description="Number of particles in the filter")
    freq_channel: FreqChannel
    track_state: Literal["init", "confirmed", "lost"]


class RadioMapUpdate(BaseMessage):
    """Radio map update — published to loc/radiomap/{freq_hz}."""

    version: str = "1.0"
    timestamp_utc: datetime
    freq_channel: FreqChannel
    bbox: dict = Field(
        ..., description="Bounding box {lat_min, lon_min, lat_max, lon_max}"
    )
    resolution_m_per_px: float
    data_b64: str = Field(..., description="float32 [H, W] array encoded as base64")


class EmitterState(BaseMessage):
    """Emitter state — published to sim/emitter/{emitter_id}."""

    version: str = "1.0"
    id: str
    lat: float
    lon: float
    alt_m: float
    freq_hz: int
    power_dbm: float
    timestamp_utc: datetime | None = None


__all__ = [
    "BaseMessage",
    "NodePosition",
    "FreqChannel",
    "RssiMessage",
    "NodeStatus",
    "TargetLocation",
    "RadioMapUpdate",
    "EmitterState",
]
